#looks like it is not needed? as I define the same in the dbt_project.yml
version: 2

models:
  - name: results
    dataset: base
    description: "base results, with vars in snake_case"
    columns:
      - name: result_id
      - name: race_id
      - name: driver_id
      - name: frastest_lap

